<a href="https://colab.research.google.com/github/rishukr02/rishukr02/blob/main/10_april_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,3,4,5,6])

In [7]:
arr1 - arr2

array([-1, -1, -1, -1, -1])

In [8]:
arr1*2 #scalar multiplication

array([ 2,  4,  6,  8, 10])

In [10]:
arr2>3

array([False, False,  True,  True,  True])

In [19]:
#dot product in matrix
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)
arr5 = arr3.dot(arr4)
arr5

array([[ 28,  31],
       [100, 112]])

In [20]:
arr5.min(axis = 0)

array([28, 31])

In [21]:
arr5.min(axis = 1)

array([ 28, 100])

In [22]:
arr6 = np.arange(0,8).reshape(2,4)
arr6

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
arr6.min(axis=0)

array([0, 1, 2, 3])

In [24]:
arr6.min(axis = 1) # axis 1 represents row nd 0 coloumn

array([0, 4])

In [25]:
arr6.sum(axis =1)

array([ 6, 22])

In [26]:
arr6.mean(axis = 0)

array([2., 3., 4., 5.])

In [27]:
arr6

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
arr6.std()

2.29128784747792

In [30]:
np.sin(arr6)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ]])

In [31]:
np.median(arr6)

3.5

In [32]:
np.mean(arr6)

3.5

In [33]:
np.exp(arr6)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03]])

In [40]:
#PANDAS
import numpy as np
import pandas as pd


In [35]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [34]:
cd/content/drive/MyDrive/PANDA

/content/drive/MyDrive/PANDA


In [38]:
!pwd

/content/drive/MyDrive/PANDA


In [41]:
data = pd.read_csv('matches - matches.csv')

In [42]:
data

id  season       city        date                        team1  \
0      1    2017  Hyderabad  2017-04-05          Sunrisers Hyderabad   
1      2    2017       Pune  2017-04-06               Mumbai Indians   
2      3    2017     Rajkot  2017-04-07                Gujarat Lions   
3      4    2017     Indore  2017-04-08       Rising Pune Supergiant   
4      5    2017  Bangalore  2017-04-08  Royal Challengers Bangalore   
..   ...     ...        ...         ...                          ...   
631  632    2016     Raipur  2016-05-22             Delhi Daredevils   
632  633    2016  Bangalore  2016-05-24                Gujarat Lions   
633  634    2016      Delhi  2016-05-25          Sunrisers Hyderabad   
634  635    2016      Delhi  2016-05-27                Gujarat Lions   
635  636    2016  Bangalore  2016-05-29          Sunrisers Hyderabad   

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1         Rising Pune Supergiant       Rising Pune Supergiant         field   
2          Kolkata Knight Riders        Kolkata Knight Riders         field   
3                Kings XI Punjab              Kings XI Punjab         field   
4               Delhi Daredevils  Royal Challengers Bangalore           bat   
..                           ...                          ...           ...   
631  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
632  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
633        Kolkata Knight Riders        Kolkata Knight Riders         field   
634          Sunrisers Hyderabad          Sunrisers Hyderabad         field   
635  Royal Challengers Bangalore          Sunrisers Hyderabad           bat   

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35   
1    normal           0       Rising Pune Supergiant            0   
2    normal           0        Kolkata Knight Riders            0   
3    normal           0              Kings XI Punjab            0   
4    normal           0  Royal Challengers Bangalore           15   
..      ...         ...                          ...          ...   
631  normal           0  Royal Challengers Bangalore            0   
632  normal           0  Royal Challengers Bangalore            0   
633  normal           0          Sunrisers Hyderabad           22   
634  normal           0          Sunrisers Hyderabad            0   
635  normal           0          Sunrisers Hyderabad            8   

     win_by_wickets player_of_match  \
0                 0    Yuvraj Singh   
1                 7       SPD Smith   
2                10         CA Lynn   
3                 6      GJ Maxwell   
4                 0       KM Jadhav   
..              ...             ...   
631               6         V Kohli   
632               4  AB de Villiers   
633               0    MC Henriques   
634               4       DA Warner   
635               0     BCJ Cutting   

                                                venue          umpire1  \
0           Rajiv Gandhi International Stadium, Uppal      AY Dandekar   
1             Maharashtra Cricket Association Stadium   A Nand Kishore   
2              Saurashtra Cricket Association Stadium      Nitin Menon   
3                              Holkar Cricket Stadium     AK Chaudhary   
4                               M Chinnaswamy Stadium              NaN   
..                                                ...              ...   
631  Shaheed Veer Narayan Singh International Stadium   A Nand Kishore   
632                             M Chinnaswamy Stadium     AK Chaudhary   
633                                  Feroz Shah Kotla        M Erasmus   
634                                  Feroz Shah Kotla        M Erasmus   
635                             M Chinnaswamy Stadium  HDPK Dharmasena   

     

In [43]:
type(data)

pandas.core.frame.DataFrame

In [44]:
data.head()#top 5 cloumns by default

id  season       city        date                        team1  \
0   1    2017  Hyderabad  2017-04-05          Sunrisers Hyderabad   
1   2    2017       Pune  2017-04-06               Mumbai Indians   
2   3    2017     Rajkot  2017-04-07                Gujarat Lions   
3   4    2017     Indore  2017-04-08       Rising Pune Supergiant   
4   5    2017  Bangalore  2017-04-08  Royal Challengers Bangalore   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1       Rising Pune Supergiant       Rising Pune Supergiant         field   
2        Kolkata Knight Riders        Kolkata Knight Riders         field   
3              Kings XI Punjab              Kings XI Punjab         field   
4             Delhi Daredevils  Royal Challengers Bangalore           bat   

   result  dl_applied                       winner  win_by_runs  \
0  normal           0          Sunrisers Hyderabad           35   
1  normal           0       Rising Pune Supergiant            0   
2  normal           0        Kolkata Knight Riders            0   
3  normal           0              Kings XI Punjab            0   
4  normal           0  Royal Challengers Bangalore           15   

   win_by_wickets player_of_match                                      venue  \
0               0    Yuvraj Singh  Rajiv Gandhi International Stadium, Uppal   
1               7       SPD Smith    Maharashtra Cricket Association Stadium   
2              10         CA Lynn     Saurashtra Cricket Association Stadium   
3               6      GJ Maxwell                     Holkar Cricket Stadium   
4               0       KM Jadhav                      M Chinnaswamy Stadium   

          umpire1        umpire2  umpire3  
0     AY Dandekar       NJ Llong      NaN  
1  A Nand Kishore         S Ravi      NaN  
2     Nitin Menon      CK Nandan      NaN  
3    AK Chaudhary  C Shamshuddin      NaN  
4             NaN            NaN      NaN

In [45]:
data.head(2)

id  season       city        date                team1  \
0   1    2017  Hyderabad  2017-04-05  Sunrisers Hyderabad   
1   2    2017       Pune  2017-04-06       Mumbai Indians   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1       Rising Pune Supergiant       Rising Pune Supergiant         field   

   result  dl_applied                  winner  win_by_runs  win_by_wickets  \
0  normal           0     Sunrisers Hyderabad           35               0   
1  normal           0  Rising Pune Supergiant            0               7   

  player_of_match                                      venue         umpire1  \
0    Yuvraj Singh  Rajiv Gandhi International Stadium, Uppal     AY Dandekar   
1       SPD Smith    Maharashtra Cricket Association Stadium  A Nand Kishore   

    umpire2  umpire3  
0  NJ Llong      NaN  
1    S Ravi      NaN

In [46]:
data.tail() #last 5 coloumns

id  season       city        date                team1  \
631  632    2016     Raipur  2016-05-22     Delhi Daredevils   
632  633    2016  Bangalore  2016-05-24        Gujarat Lions   
633  634    2016      Delhi  2016-05-25  Sunrisers Hyderabad   
634  635    2016      Delhi  2016-05-27        Gujarat Lions   
635  636    2016  Bangalore  2016-05-29  Sunrisers Hyderabad   

                           team2                  toss_winner toss_decision  \
631  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
632  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
633        Kolkata Knight Riders        Kolkata Knight Riders         field   
634          Sunrisers Hyderabad          Sunrisers Hyderabad         field   
635  Royal Challengers Bangalore          Sunrisers Hyderabad           bat   

     result  dl_applied                       winner  win_by_runs  \
631  normal           0  Royal Challengers Bangalore            0   
632  normal           0  Royal Challengers Bangalore            0   
633  normal           0          Sunrisers Hyderabad           22   
634  normal           0          Sunrisers Hyderabad            0   
635  normal           0          Sunrisers Hyderabad            8   

     win_by_wickets player_of_match  \
631               6         V Kohli   
632               4  AB de Villiers   
633               0    MC Henriques   
634               4       DA Warner   
635               0     BCJ Cutting   

                                                venue          umpire1  \
631  Shaheed Veer Narayan Singh International Stadium   A Nand Kishore   
632                             M Chinnaswamy Stadium     AK Chaudhary   
633                                  Feroz Shah Kotla        M Erasmus   
634                                  Feroz Shah Kotla        M Erasmus   
635                             M Chinnaswamy Stadium  HDPK Dharmasena   

             umpire2  umpire3  
631     BNJ Oxenford      NaN  
632  HDPK Dharmasena      NaN  
633    C Shamshuddin      NaN  
634        CK Nandan      NaN  
635     BNJ Oxenford      NaN

In [47]:
data.shape

(636, 18)

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               636 non-null    int64  
 1   season           636 non-null    int64  
 2   city             629 non-null    object 
 3   date             636 non-null    object 
 4   team1            636 non-null    object 
 5   team2            636 non-null    object 
 6   toss_winner      636 non-null    object 
 7   toss_decision    636 non-null    object 
 8   result           636 non-null    object 
 9   dl_applied       636 non-null    int64  
 10  winner           633 non-null    object 
 11  win_by_runs      636 non-null    int64  
 12  win_by_wickets   636 non-null    int64  
 13  player_of_match  633 non-null    object 
 14  venue            636 non-null    object 
 15  umpire1          635 non-null    object 
 16  umpire2          635 non-null    object 
 17  umpire3         

In [49]:
data.describe()

id       season  dl_applied  win_by_runs  win_by_wickets  \
count  636.000000   636.000000  636.000000   636.000000      636.000000   
mean   318.500000  2012.490566    0.025157    13.682390        3.372642   
std    183.741666     2.773026    0.156726    23.908877        3.420338   
min      1.000000  2008.000000    0.000000     0.000000        0.000000   
25%    159.750000  2010.000000    0.000000     0.000000        0.000000   
50%    318.500000  2012.000000    0.000000     0.000000        4.000000   
75%    477.250000  2015.000000    0.000000    20.000000        7.000000   
max    636.000000  2017.000000    1.000000   146.000000       10.000000   

       umpire3  
count      0.0  
mean       NaN  
std        NaN  
min        NaN  
25%        NaN  
50%        NaN  
75%        NaN  
max        NaN

In [51]:
data["winner"]

0              Sunrisers Hyderabad
1           Rising Pune Supergiant
2            Kolkata Knight Riders
3                  Kings XI Punjab
4      Royal Challengers Bangalore
                  ...             
631    Royal Challengers Bangalore
632    Royal Challengers Bangalore
633            Sunrisers Hyderabad
634            Sunrisers Hyderabad
635            Sunrisers Hyderabad
Name: winner, Length: 636, dtype: object

In [52]:
data["winner"].shape

(636,)

In [54]:
data[["team1","team2","winner"]] #how to fetch multiple coloumns

team1                        team2  \
0            Sunrisers Hyderabad  Royal Challengers Bangalore   
1                 Mumbai Indians       Rising Pune Supergiant   
2                  Gujarat Lions        Kolkata Knight Riders   
3         Rising Pune Supergiant              Kings XI Punjab   
4    Royal Challengers Bangalore             Delhi Daredevils   
..                           ...                          ...   
631             Delhi Daredevils  Royal Challengers Bangalore   
632                Gujarat Lions  Royal Challengers Bangalore   
633          Sunrisers Hyderabad        Kolkata Knight Riders   
634                Gujarat Lions          Sunrisers Hyderabad   
635          Sunrisers Hyderabad  Royal Challengers Bangalore   

                          winner  
0            Sunrisers Hyderabad  
1         Rising Pune Supergiant  
2          Kolkata Knight Riders  
3                Kings XI Punjab  
4    Royal Challengers Bangalore  
..                           ...  
631  Royal Challengers Bangalore  
632  Royal Challengers Bangalore  
633          Sunrisers Hyderabad  
634          Sunrisers Hyderabad  
635          Sunrisers Hyderabad  

[636 rows x 3 columns]

In [56]:
data.iloc[0]

id                                                         1
season                                                  2017
city                                               Hyderabad
date                                              2017-04-05
team1                                    Sunrisers Hyderabad
team2                            Royal Challengers Bangalore
toss_winner                      Royal Challengers Bangalore
toss_decision                                          field
result                                                normal
dl_applied                                                 0
winner                                   Sunrisers Hyderabad
win_by_runs                                               35
win_by_wickets                                             0
player_of_match                                 Yuvraj Singh
venue              Rajiv Gandhi International Stadium, Uppal
umpire1                                          AY Dandekar
umpire2                 

In [57]:
data.iloc[1]

id                                                       2
season                                                2017
city                                                  Pune
date                                            2017-04-06
team1                                       Mumbai Indians
team2                               Rising Pune Supergiant
toss_winner                         Rising Pune Supergiant
toss_decision                                        field
result                                              normal
dl_applied                                               0
winner                              Rising Pune Supergiant
win_by_runs                                              0
win_by_wickets                                           7
player_of_match                                  SPD Smith
venue              Maharashtra Cricket Association Stadium
umpire1                                     A Nand Kishore
umpire2                                             S Ra

In [58]:
data.iloc[1:3]

id  season    city        date           team1                   team2  \
1   2    2017    Pune  2017-04-06  Mumbai Indians  Rising Pune Supergiant   
2   3    2017  Rajkot  2017-04-07   Gujarat Lions   Kolkata Knight Riders   

              toss_winner toss_decision  result  dl_applied  \
1  Rising Pune Supergiant         field  normal           0   
2   Kolkata Knight Riders         field  normal           0   

                   winner  win_by_runs  win_by_wickets player_of_match  \
1  Rising Pune Supergiant            0               7       SPD Smith   
2   Kolkata Knight Riders            0              10         CA Lynn   

                                     venue         umpire1    umpire2  umpire3  
1  Maharashtra Cricket Association Stadium  A Nand Kishore     S Ravi      NaN  
2   Saurashtra Cricket Association Stadium     Nitin Menon  CK Nandan      NaN

In [59]:
type(data.iloc[1:3])

pandas.core.frame.DataFrame

In [60]:
data.iloc[1:11:2]

id  season       city        date                        team1  \
1   2    2017       Pune  2017-04-06               Mumbai Indians   
3   4    2017     Indore  2017-04-08       Rising Pune Supergiant   
5   6    2017  Hyderabad  2017-04-09                Gujarat Lions   
7   8    2017     Indore  2017-04-10  Royal Challengers Bangalore   
9  10    2017     Mumbai  2017-04-12          Sunrisers Hyderabad   

                    team2                  toss_winner toss_decision  result  \
1  Rising Pune Supergiant       Rising Pune Supergiant         field  normal   
3         Kings XI Punjab              Kings XI Punjab         field  normal   
5     Sunrisers Hyderabad          Sunrisers Hyderabad         field  normal   
7         Kings XI Punjab  Royal Challengers Bangalore           bat  normal   
9          Mumbai Indians               Mumbai Indians         field  normal   

   dl_applied                  winner  win_by_runs  win_by_wickets  \
1           0  Rising Pune Supergiant            0               7   
3           0         Kings XI Punjab            0               6   
5           0     Sunrisers Hyderabad            0               9   
7           0         Kings XI Punjab            0               8   
9           0          Mumbai Indians            0               4   

  player_of_match                                      venue         umpire1  \
1       SPD Smith    Maharashtra Cricket Association Stadium  A Nand Kishore   
3      GJ Maxwell                     Holkar Cricket Stadium    AK Chaudhary   
5     Rashid Khan  Rajiv Gandhi International Stadium, Uppal      A Deshmukh   
7        AR Patel                     Holkar Cricket Stadium    AK Chaudhary   
9       JJ Bumrah                           Wankhede Stadium     Nitin Menon   

         umpire2  umpire3  
1         S Ravi      NaN  
3  C Shamshuddin      NaN  
5       NJ Llong      NaN  
7  C Shamshuddin      NaN  
9      CK Nandan      NaN

In [61]:
data.iloc[[1,3,6]]

id  season    city        date                   team1  \
1   2    2017    Pune  2017-04-06          Mumbai Indians   
3   4    2017  Indore  2017-04-08  Rising Pune Supergiant   
6   7    2017  Mumbai  2017-04-09   Kolkata Knight Riders   

                    team2             toss_winner toss_decision  result  \
1  Rising Pune Supergiant  Rising Pune Supergiant         field  normal   
3         Kings XI Punjab         Kings XI Punjab         field  normal   
6          Mumbai Indians          Mumbai Indians         field  normal   

   dl_applied                  winner  win_by_runs  win_by_wickets  \
1           0  Rising Pune Supergiant            0               7   
3           0         Kings XI Punjab            0               6   
6           0          Mumbai Indians            0               4   

  player_of_match                                    venue         umpire1  \
1       SPD Smith  Maharashtra Cricket Association Stadium  A Nand Kishore   
3      GJ Maxwell                   Holkar Cricket Stadium    AK Chaudhary   
6          N Rana                         Wankhede Stadium     Nitin Menon   

         umpire2  umpire3  
1         S Ravi      NaN  
3  C Shamshuddin      NaN  
6      CK Nandan      NaN

In [63]:
data.iloc[:,[3,5,8]]

date                        team2  result
0    2017-04-05  Royal Challengers Bangalore  normal
1    2017-04-06       Rising Pune Supergiant  normal
2    2017-04-07        Kolkata Knight Riders  normal
3    2017-04-08              Kings XI Punjab  normal
4    2017-04-08             Delhi Daredevils  normal
..          ...                          ...     ...
631  2016-05-22  Royal Challengers Bangalore  normal
632  2016-05-24  Royal Challengers Bangalore  normal
633  2016-05-25        Kolkata Knight Riders  normal
634  2016-05-27          Sunrisers Hyderabad  normal
635  2016-05-29  Royal Challengers Bangalore  normal

[636 rows x 3 columns]