<a href="https://colab.research.google.com/github/rishukr02/rishukr02/blob/main/8_april_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY - LIBRARY WRITTEN IN 'C' & FORTRAM MATHEMATICAL OPERATIONS


In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4,5])

In [ ]:
arr3 = np.array([5,6,7,9,8])

In [ ]:
arr2 = np.array([1,2,3,4]),([2,4,6,7])

In [ ]:
arr5 = np.identity

In [ ]:
arr9 = np.linspace(10,20,10)
arr9

In [ ]:
# NUMPY ARRAY PROPERTIES AND ATTRIBUTES

In [ ]:
arr.shape

In [ ]:
arr11 = np.array([[11, 12, 13], [14, 15, 16]])
arr11.ndim


2

In [ ]:
arr11.size

In [ ]:
arr11.itemsize

In [ ]:
arr12 = np.array([1,6,7,5])

In [ ]:
arr3.dtype

dtype('int64')

In [ ]:
import numpy as np
arr23 = np.array([[1, 2, 3], [4, 5, 6]])
arr23.dtype



dtype('int64')

In [ ]:
my_list = list(range(100))
array1 = np.arrange(100)

In [ ]:
print(array1.itemsize*arr1.size)

In [ ]:
import sys


In [ ]:
sys.getsizeof(9)

28

In [ ]:
import time
x = range(1000)
y = range(1000,2000)
start_time = time.time()
c = [(x + y) for x,y in zip(x,y)]
print(time.time() - start_time)


0.0004112720489501953


In [ ]:
import numpy as np
import time

a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start_time = time.time()
c = a + b
print("Time taken:", time.time() - start_time)

Time taken: 0.09433674812316895


In [ ]:
#INDEXING AND SLICING IN NUMPY ARRAYS


In [ ]:

import numpy as np

arr12 = np.arange(24)
print(arr12)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
arr12 = arr12.reshape((6, 4))
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr13 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr13[3]

4

In [ ]:
arr13[2:3]

array([3])

In [ ]:
arr13[2:4]

array([3, 4])

In [ ]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr14=arr12.reshape(6,4)
arr14

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr14[2]

array([ 8,  9, 10, 11])

In [ ]:
arr14[2:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr14[:,2]   #column value

array([ 2,  6, 10, 14, 18, 22])

In [ ]:
arr14[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [ ]:
arr14[4:,2:]

array([[18, 19],
       [22, 23]])